#!/bin/bash

IMAGE_TAG=cpg2dot

# if the image exists already, run the following command beforehand (clean up):
# docker rmi -f $IMAGE_TAG
if [[ "$(docker images -q $IMAGE_TAG 2> /dev/null)" == "" ]]; then
    docker build . -t $IMAGE_TAG
fi
